# Site settings
title: My Documentation
description: Personal notes and documentation
url: "http://localhost:4000"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default frontmatter
defaults:
  - scope:
      path: "_docs"
    values:
      layout: "doc"
      nav_exclude: false

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/