remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Documentation Site
description: A collection of documentation with Mermaid diagrams
show_downloads: false

# Navigation structure
header_pages:
  - docs/index.md

# Enable mermaid diagram processing
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  
# Add custom scripts
mermaid:
  version: "9.4.3"
