remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Documentation Site
description: A collection of documentation with Mermaid diagrams
show_downloads: false

# Navigation
header_pages:
  - docs/index.md

# Site settings
url: "" # the base hostname & protocol
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_options:
    disable: true
  syntax_highlighter: rouge
  
# Mermaid configuration
mermaid:
  src: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.4.3/mermaid.min.js'

# Default layout for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "docs"
    values:
      layout: "default"
